//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
[XmlRoot("xml")]
public partial class SearchXML {
    
    private decimal query_timeField;
    
    private string suggested_spellingField;
    
    private object custom_synonymsField;
    
    private xmlPagination paginationField;
    
    private string searched_in_fieldField;
    
    private object user_search_depthField;
    
    private string currently_sorted_byField;
    
    private string[] sort_bysField;
    
    private xmlNotices noticesField;
    
    private xmlMerchandizing merchandizingField;
    
    private xmlRefinable[] refinablesField;
    
    private xmlResult[] resultsField;
    
    private int xml_feed_doneField;
    
    private uint clField;
    
    /// <remarks/>
    public decimal query_time {
        get {
            return this.query_timeField;
        }
        set {
            this.query_timeField = value;
        }
    }
    
    /// <remarks/>
    public string suggested_spelling {
        get {
            return this.suggested_spellingField;
        }
        set {
            this.suggested_spellingField = value;
        }
    }
    
    /// <remarks/>
    public object custom_synonyms {
        get {
            return this.custom_synonymsField;
        }
        set {
            this.custom_synonymsField = value;
        }
    }
    
    /// <remarks/>
    public xmlPagination pagination {
        get {
            return this.paginationField;
        }
        set {
            this.paginationField = value;
        }
    }
    
    /// <remarks/>
    public string searched_in_field {
        get {
            return this.searched_in_fieldField;
        }
        set {
            this.searched_in_fieldField = value;
        }
    }
    
    /// <remarks/>
    public object user_search_depth {
        get {
            return this.user_search_depthField;
        }
        set {
            this.user_search_depthField = value;
        }
    }
    
    /// <remarks/>
    public string currently_sorted_by {
        get {
            return this.currently_sorted_byField;
        }
        set {
            this.currently_sorted_byField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("sort_by", IsNullable=false)]
    public string[] sort_bys {
        get {
            return this.sort_bysField;
        }
        set {
            this.sort_bysField = value;
        }
    }
    
    /// <remarks/>
    public xmlNotices notices {
        get {
            return this.noticesField;
        }
        set {
            this.noticesField = value;
        }
    }
    
    /// <remarks/>
    public xmlMerchandizing merchandizing {
        get {
            return this.merchandizingField;
        }
        set {
            this.merchandizingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("refinable", IsNullable=false)]
    public xmlRefinable[] refinables {
        get {
            return this.refinablesField;
        }
        set {
            this.refinablesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable=false)]
    public xmlResult[] results {
        get {
            return this.resultsField;
        }
        set {
            this.resultsField = value;
        }
    }
    
    /// <remarks/>
    public int xml_feed_done {
        get {
            return this.xml_feed_doneField;
        }
        set {
            this.xml_feed_doneField = value;
        }
    }
    
    /// <remarks/>
    public uint cl {
        get {
            return this.clField;
        }
        set {
            this.clField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class xmlPagination {
    
    private int total_productsField;
    
    private int product_minField;
    
    private int product_maxField;
    
    private int current_pageField;
    
    private int total_pagesField;
    
    private int prev_pageField;
    
    private int next_pageField;
    
    /// <remarks/>
    public int total_products {
        get {
            return this.total_productsField;
        }
        set {
            this.total_productsField = value;
        }
    }
    
    /// <remarks/>
    public int product_min {
        get {
            return this.product_minField;
        }
        set {
            this.product_minField = value;
        }
    }
    
    /// <remarks/>
    public int product_max {
        get {
            return this.product_maxField;
        }
        set {
            this.product_maxField = value;
        }
    }
    
    /// <remarks/>
    public int current_page {
        get {
            return this.current_pageField;
        }
        set {
            this.current_pageField = value;
        }
    }
    
    /// <remarks/>
    public int total_pages {
        get {
            return this.total_pagesField;
        }
        set {
            this.total_pagesField = value;
        }
    }
    
    /// <remarks/>
    public int prev_page {
        get {
            return this.prev_pageField;
        }
        set {
            this.prev_pageField = value;
        }
    }
    
    /// <remarks/>
    public int next_page {
        get {
            return this.next_pageField;
        }
        set {
            this.next_pageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class xmlNotices {
    
    private string related_addedField;
    
    private string sku_matchField;
    
    private string or_switchField;
    
    /// <remarks/>
    public string related_added {
        get {
            return this.related_addedField;
        }
        set {
            this.related_addedField = value;
        }
    }
    
    /// <remarks/>
    public string sku_match {
        get {
            return this.sku_matchField;
        }
        set {
            this.sku_matchField = value;
        }
    }
    
    /// <remarks/>
    public string or_switch {
        get {
            return this.or_switchField;
        }
        set {
            this.or_switchField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class xmlMerchandizing {
    
    private string html_codeField;
    
    /// <remarks/>
    public string html_code {
        get {
            return this.html_codeField;
        }
        set {
            this.html_codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class xmlRefinable {
    
    private string nameField;
    
    private xmlRefinableValue[] valuesField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
    public xmlRefinableValue[] values {
        get {
            return this.valuesField;
        }
        set {
            this.valuesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class xmlRefinableValue {
    
    private string nameField;
    
    private int numField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public int num {
        get {
            return this.numField;
        }
        set {
            this.numField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class xmlResult {
    
    private int rankField;
    
    private string skuField;
    
    private string nameField;
    
    private string priceField;
    
    private string descriptionField;
    
    private string producturlField;
    
    private string categoryField;
    
    private string productidField;
    
    private string manufacturerpartnumberField;
    
    private string manufacturerField;
    
    private string subcategoryField;
    
    private string generationField;
    
    private string imageField;
    
    private string scoreField;
    
    private string nameindexField;
    
    private string descindexField;
    
    private string thumbnailField;
    
    private string iconField;
    
    private string nxtpartnumberField;
    
    private string drilldownField;
    
    private string onsaleField;
    
    private string averageratingField;
    
    private string totalreviewsField;
    
    private string idField;
    
    /// <remarks/>
    public int rank {
        get {
            return this.rankField;
        }
        set {
            this.rankField = value;
        }
    }
    
    /// <remarks/>
    public string Sku {
        get {
            return this.skuField;
        }
        set {
            this.skuField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Producturl {
        get {
            return this.producturlField;
        }
        set {
            this.producturlField = value;
        }
    }
    
    /// <remarks/>
    public string Category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    public string Productid {
        get {
            return this.productidField;
        }
        set {
            this.productidField = value;
        }
    }
    
    /// <remarks/>
    public string Manufacturerpartnumber {
        get {
            return this.manufacturerpartnumberField;
        }
        set {
            this.manufacturerpartnumberField = value;
        }
    }
    
    /// <remarks/>
    public string Manufacturer {
        get {
            return this.manufacturerField;
        }
        set {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    public string Subcategory {
        get {
            return this.subcategoryField;
        }
        set {
            this.subcategoryField = value;
        }
    }
    
    /// <remarks/>
    public string Generation {
        get {
            return this.generationField;
        }
        set {
            this.generationField = value;
        }
    }
    
    /// <remarks/>
    public string Image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    public string Score {
        get {
            return this.scoreField;
        }
        set {
            this.scoreField = value;
        }
    }
    
    /// <remarks/>
    public string Nameindex {
        get {
            return this.nameindexField;
        }
        set {
            this.nameindexField = value;
        }
    }
    
    /// <remarks/>
    public string Descindex {
        get {
            return this.descindexField;
        }
        set {
            this.descindexField = value;
        }
    }
    
    /// <remarks/>
    public string Thumbnail {
        get {
            return this.thumbnailField;
        }
        set {
            this.thumbnailField = value;
        }
    }
    
    /// <remarks/>
    public string Icon {
        get {
            return this.iconField;
        }
        set {
            this.iconField = value;
        }
    }
    
    /// <remarks/>
    public string Nxtpartnumber {
        get {
            return this.nxtpartnumberField;
        }
        set {
            this.nxtpartnumberField = value;
        }
    }
    
    /// <remarks/>
    public string Drilldown {
        get {
            return this.drilldownField;
        }
        set {
            this.drilldownField = value;
        }
    }
    
    /// <remarks/>
    public string Onsale {
        get {
            return this.onsaleField;
        }
        set {
            this.onsaleField = value;
        }
    }
    
    /// <remarks/>
    public string Averagerating {
        get {
            return this.averageratingField;
        }
        set {
            this.averageratingField = value;
        }
    }
    
    /// <remarks/>
    public string Totalreviews {
        get {
            return this.totalreviewsField;
        }
        set {
            this.totalreviewsField = value;
        }
    }
    
    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}
